version: "3"
services:

  pg:
    image: postgres:16.1
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build:
      context: ../
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
          max-size: "1g"
    volumes:
      - ../:/app
    depends_on:
      - pg
    command: uvicorn app:app --host 0.0.0.0 --port 80

  tg_bot:
    build:
      context: ../
    env_file:
      - ./.env
    command: python bot.py
    volumes:
      - ../:/app
    depends_on:
      - pg

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    volumes:
      - ./nginx.conf/:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: